#!/bin/bash
#SBATCH --job-name=run-bayeswave-3det  # Job name
#SBATCH --nodes=1               # Number of nodes
#SBATCH --ntasks=1              # Number of tasks
#SBATCH --cpus-per-task=20
#SBATCH --hint=multithread
#SBATCH --time=24:00:30         # Time limit
#SBATCH --partition=shared      # Partition name
#SBATCH --account=phy240043   # Account name
#SBATCH --array=0-11            # Array range for 12 three_detectors directories
#SBATCH --output=/anvil/scratch/x-ctirapongpra/jobout/%x_%A_%a.out  # Output file for each array task
#SBATCH --error=/anvil/scratch/x-ctirapongpra/jobout/%x_%A_%a.out   # Error file for each array task

module load anaconda
conda activate bayeswave-cpp-copy

# Array of three_detectors directories
SUBFOLDERS=(
    "full_signal_x_amp_0.10"
    "full_signal_x_amp_0.20"
    "full_signal_x_amp_0.30"
    "full_signal_x_amp_0.40"
    "full_signal_x_amp_0.50"
    "full_signal_x_amp_0.60"
    "full_signal_z_amp_0.05"
    "full_signal_z_amp_0.10"
    "full_signal_z_amp_0.15"
    "full_signal_z_amp_0.20"
    "full_signal_z_amp_0.25"
    "full_signal_z_amp_0.30"
)

# Select directory based on array task ID
DIR=${SUBFOLDERS[$SLURM_ARRAY_TASK_ID]}

export OMP_NUM_THREADS=20 # Set the number of OpenMP threads

# Navigate to the specific three_detectors directory and run output.sh
cd /anvil/scratch/x-ctirapongpra/gw-collapsar/three_detectors/${DIR}
bash output/output.sh
